[platformio]
src_dir = ./

[env:gbs2cpc]
platform = espressif8266@4.2.1
board = d1_mini
framework = arduino
board_build.f_cpu = 160000000L
board_build.ldscript = eagle.flash.4m1m.ld
board_build.filesystem = littlefs
board_build.flash_mode = qio
upload_speed = 460800
monitor_speed = 115200

